# StaySense

## Notebook 01 – Data Understanding

### Objective

The goal of this notebook is to understand the Airbnb datasets before performing any cleaning or analysis.

### Business Questions

- What data do we have?
- How are the datasets connected?
- Which columns are useful?
- What business problems can this data solve?
- What are the limitations of the data?

In [1]:
import pandas as pd
import numpy as np

# Show all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", None)

In [ ]:
listings = pd.read_csv("../Data/raw/Listings.csv", encoding="latin-1")
reviews = pd.read_csv("../Data/raw/Reviews.csv", encoding="latin-1")

C:\Users\Parv Gupta\AppData\Local\Temp\ipykernel_2948\2050404675.py:1: DtypeWarning: Columns (5,13) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv("../data/raw/Listings.csv", encoding="latin-1")

In [3]:
print("Listings Shape:", listings.shape)
print("Reviews Shape:", reviews.shape)

Listings Shape: (279712, 33)
Reviews Shape: (5373143, 4)

In [4]:
listings.head()

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,district,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,amenities,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Buttes-Montmartre,NaN,Paris,48.88668,2.33343,Entire apartment,Entire place,2,1.0,"[""Heating"", ""Kitchen"", ""Washer"", ""Wifi"", ""Long...",53,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,t,Buttes-Montmartre,NaN,Paris,48.88617,2.34515,Entire apartment,Entire place,2,1.0,"[""Shampoo"", ""Heating"", ""Kitchen"", ""Essentials""...",120,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Elysee,NaN,Paris,48.88112,2.31712,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Washer"", ""Wifi"",...",89,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,t,Vaugirard,NaN,Paris,48.84571,2.30584,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Wifi"", ""Long ter...",58,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Passy,NaN,Paris,48.85500,2.26979,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Essentials"", ""Ha...",60,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [5]:
reviews.head()

   listing_id  review_id        date  reviewer_id
0       11798  330265172  2018-09-30     11863072
1       15383  330103585  2018-09-30     39147453
2       16455  329985788  2018-09-30      1125378
3       17919  330016899  2018-09-30    172717984
4       26827  329995638  2018-09-30     17542859

In [6]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279537 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  object
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: float64(13), int64(6), object(14)
memory usage: 70.4+ MB

In [7]:
missing_values = listings.isnull().sum()

missing_percentage = (missing_values / len(listings)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

missing_df.sort_values(by="Missing Percentage", ascending=False)

                             Missing Values  Missing Percentage
district                             242700           86.767818
host_response_time                   128782           46.040928
host_response_rate                   128782           46.040928
host_acceptance_rate                 113087           40.429799
review_scores_value                   91785           32.814109
review_scores_location                91775           32.810534
review_scores_checkin                 91771           32.809104
review_scores_accuracy                91713           32.788368
review_scores_communication           91687           32.779073
review_scores_cleanliness             91665           32.771208
review_scores_rating                  91405           32.678255
bedrooms                              29435           10.523324
host_location                           840            0.300309
name                                    175            0.062564
host_identity_verified                  165            0.058989
host_has_profile_pic                    165            0.058989
host_is_superhost                       165            0.058989
host_since                              165            0.058989
host_total_listings_count               165            0.058989
listing_id                                0            0.000000
minimum_nights                            0            0.000000
maximum_nights                            0            0.000000
longitude                                 0            0.000000
price                                     0            0.000000
amenities                                 0            0.000000
accommodates                              0            0.000000
room_type                                 0            0.000000
property_type                             0            0.000000
latitude                                  0            0.000000
city                                      0            0.000000
neighbourhood                             0            0.000000
host_id                                   0            0.000000
instant_bookable                          0            0.000000

## Decision #1

Column: district

Reason:
- 87% missing values.
- Geographic information is already available through city, neighbourhood, latitude, and longitude.
- Does not significantly contribute to the business questions we want to answer.

Decision:
Drop during the data cleaning phase.

In [8]:
listings.describe()

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
count,2.797120e+05,2.797120e+05,150930.000000,166625.000000,279547.000000,279712.000000,279712.000000,279712.000000,250277.000000,279712.000000,279712.000000,2.797120e+05,188307.000000,187999.000000,188047.000000,187941.000000,188025.000000,187937.000000,187927.000000
mean,2.638196e+07,1.081658e+08,0.865939,0.827168,24.581612,18.761862,12.595075,3.288736,1.515509,608.792737,8.050967,2.755860e+04,93.405195,9.565476,9.312869,9.701534,9.698593,9.633994,9.335364
std,1.442576e+07,1.108570e+08,0.283744,0.289202,284.041143,32.560343,73.081309,2.133379,1.153080,3441.826611,31.518946,7.282875e+06,10.070437,0.990878,1.146072,0.867434,0.886884,0.833234,1.042625
min,2.577000e+03,1.822000e+03,0.000000,0.000000,0.000000,-34.264400,-99.339630,0.000000,1.000000,0.000000,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.384462e+07,1.720656e+07,0.900000,0.780000,1.000000,-22.964390,-43.198040,2.000000,1.000000,75.000000,1.000000,4.500000e+01,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000
50%,2.767098e+07,5.826911e+07,1.000000,0.980000,1.000000,40.710785,2.382780,2.000000,1.000000,150.000000,2.000000,1.125000e+03,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
75%,3.978485e+07,1.832853e+08,1.000000,1.000000,4.000000,41.908610,28.986730,4.000000,2.000000,474.000000,5.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
max,4.834353e+07,3.901874e+08,1.000000,1.000000,7235.000000,48.904910,151.339810,16.000000,50.000000,625216.000000,9999.000000,2.147484e+09,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

## Observation 4

Price

Mean = 608
Median = 150

Large difference suggests a right-skewed distribution and possible high-value outliers.

---

## Observation 5

Minimum price = 0

Needs investigation during cleaning.

---

## Observation 6

Maximum nights = 2,147,483,647

Likely represents a placeholder or "no limit" value rather than a true booking limit.

---

## Observation 7

Accommodates

Minimum = 0

Impossible value.

Requires investigation.

In [9]:
listings.describe(include="object")

,name,host_since,host_location,host_response_time,host_is_superhost,host_has_profile_pic,host_identity_verified,neighbourhood,district,city,property_type,room_type,amenities,instant_bookable
count,279537,279547,278872,150930,279547,279547,279547,279712,37012,279712,279712,279712,279712,279712
unique,265860,4240,7159,4,2,2,2,660,5,10,144,4,245003,2
top,home away from home,2019-09-02,"Paris, Ile-de-France, France",within an hour,f,t,t,I Centro Storico,Manhattan,Paris,Entire apartment,Entire place,"[""Long term stays allowed""]",f
freq,98,710,47794,83464,229294,278631,201191,14874,16553,64690,138989,182005,1388,164105

In [10]:
listings.duplicated().sum()

np.int64(0)

In [11]:
listings["listing_id"].duplicated().sum()

np.int64(0)

In [12]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5373143 entries, 0 to 5373142
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   listing_id   int64
 1   review_id    int64
 2   date         object
 3   reviewer_id  int64
dtypes: int64(3), object(1)
memory usage: 164.0+ MB

In [13]:
reviews.head()

   listing_id  review_id        date  reviewer_id
0       11798  330265172  2018-09-30     11863072
1       15383  330103585  2018-09-30     39147453
2       16455  329985788  2018-09-30      1125378
3       17919  330016899  2018-09-30    172717984
4       26827  329995638  2018-09-30     17542859

In [14]:
reviews["listing_id"].value_counts().head()

listing_id
17222007    891
8637229     828
1249964     796
32011332    762
2399029     754
Name: count, dtype: int64